# Generated by Django 4.0.4 on 2022-07-05 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_delete_myuploadfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=20, unique=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('nhiss', models.IntegerField()),
                ('mrs', models.IntegerField()),
                ('systolic', models.IntegerField()),
                ('distolic', models.IntegerField()),
                ('glucose', models.IntegerField()),
                ('paralysis', models.IntegerField()),
                ('smoking', models.IntegerField()),
                ('bmi', models.IntegerField()),
                ('cholesterol', models.IntegerField()),
                ('tos', models.IntegerField()),
                ('risk', models.IntegerField()),
            ],
        ),
    ]
